import { createFileRoute, Link } from "@tanstack/react-router"
import { AlertTriangle, CheckCircle2, FolderKanban, ListChecks } from "lucide-react"
import { useEffect, useState } from "react"

export const Route = createFileRoute("/_layout/")({ component: Dashboard, head: () => ({ meta: [{ title: "Dashboard - Vexa" }] }) })
type Analytics = { project_count: number; active_stages: number; completed_stages: number; test_case_count: number; reviewed_case_count: number; passed_step_count: number; total_step_count: number; failed_step_count: number; blocked_case_count: number }
type Project = { id: string; name: string; description?: string | null }
async function request(path: string) { const headers = new Headers(); const token = localStorage.getItem("access_token"); if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(`/api/v1${path}`, { headers }); if (!response.ok) throw new Error("Unable to load dashboard"); return response.json() }
function Metric({ label, value, icon: Icon, tone = "" }: { label: string; value: string | number; icon: typeof FolderKanban; tone?: string }) { return <div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className={`size-4 ${tone}`} /></div><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p></div> }
function Dashboard() {
  const [analytics, setAnalytics] = useState<Analytics | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState("")
  useEffect(() => { Promise.all([request("/projects/analytics"), request("/projects/")]).then(([a, p]) => { setAnalytics(a); setProjects(p.data) }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load dashboard")) }, [])
  if (error) return <p className="text-sm text-destructive" role="alert">{error}</p>
  if (!analytics) return <p className="text-sm text-muted-foreground">Loading dashboard…</p>
  const executionRate = analytics.total_step_count ? `${Math.round(analytics.passed_step_count / analytics.total_step_count * 100)}%` : "0%"
  return <div className="mx-auto flex max-w-7xl flex-col gap-7"><div><h1 className="text-2xl font-semibold tracking-tight">Dashboard</h1><p className="mt-1 text-muted-foreground">Qualification progress across your projects.</p></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Projects" value={analytics.project_count} icon={FolderKanban} /><Metric label="Active stages" value={analytics.active_stages} icon={ListChecks} /><Metric label="Test cases" value={analytics.test_case_count} icon={ListChecks} /><Metric label="Execution progress" value={executionRate} icon={CheckCircle2} tone="text-emerald-600" /></section><section className="grid gap-4 lg:grid-cols-3"><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-medium">Workflow status</h2><div className="mt-4 grid gap-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Completed stages</span><span>{analytics.completed_stages}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Reviewed cases</span><span>{analytics.reviewed_case_count} / {analytics.test_case_count}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Passed steps</span><span>{analytics.passed_step_count} / {analytics.total_step_count}</span></div></div></div><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-medium">Needs attention</h2>{analytics.blocked_case_count || analytics.failed_step_count ? <div className="mt-4 flex items-start gap-3 text-sm text-red-600"><AlertTriangle className="mt-0.5 size-4 shrink-0" /><p>{analytics.blocked_case_count} blocked case{analytics.blocked_case_count === 1 ? "" : "s"} · {analytics.failed_step_count} failed step{analytics.failed_step_count === 1 ? "" : "s"}</p></div> : <div className="mt-4 flex items-start gap-3 text-sm text-emerald-600"><CheckCircle2 className="mt-0.5 size-4" /><p>No blocked or failed steps.</p></div>}</div><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-medium">Projects</h2><div className="mt-3 grid gap-2">{projects.slice(0, 5).map((project) => <Link key={project.id} to="/projects/$projectId" params={{ projectId: project.id }} className="rounded-md border border-border px-3 py-2 text-sm hover:bg-muted">{project.name}</Link>)}{!projects.length && <p className="text-sm text-muted-foreground">No projects yet.</p>}</div></div></section></div>
}
