import { Search } from "lucide-react"
import { useEffect, useState } from "react"

type Step = { id: string; step_number: number; action: string }
type Reference = { id: string; title: string; source_url: string; image_url?: string | null; snippet?: string | null; publisher?: string | null }

export function StepVisualGuidance({ projectId, caseId, steps }: { projectId: string; caseId: string; steps: Step[] }) {
  const [selected, setSelected] = useState(steps[0]?.id || ""); const [query, setQuery] = useState(""); const [references, setReferences] = useState<Reference[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("")
  async function load() { const token = localStorage.getItem("access_token"); const response = await fetch(`/api/v1/projects/${projectId}/visuals?case_id=${caseId}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (response.ok) setReferences(await response.json()) }
  useEffect(() => { void load() }, [projectId, caseId])
  const active = steps.find((step) => step.id === selected)
  async function search() { if (!active) return; setBusy(true); setError(""); try { const token = localStorage.getItem("access_token"); const response = await fetch(`/api/v1/projects/${projectId}/visuals/search`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ case_id: caseId, step_id: active.id, query: query || active.action }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Visual search failed"); setReferences((current) => [...data.references, ...current]) } catch (reason) { setError(reason instanceof Error ? reason.message : "Visual search failed") } finally { setBusy(false) } }
  return <section className="grid gap-3 rounded-lg border border-border bg-card p-4"><div><h2 className="font-medium">Visual guidance</h2><p className="mt-1 text-sm text-muted-foreground">Find reference images for the selected protocol step. These references guide the operator; they are not acceptance evidence.</p></div><div className="flex flex-wrap gap-2">{steps.map((step) => <button type="button" key={step.id} onClick={() => setSelected(step.id)} className={`rounded-md border px-2.5 py-1.5 text-xs ${selected === step.id ? "border-foreground bg-muted" : "border-border hover:bg-muted"}`}>Step {step.step_number}</button>)}</div><div className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={active?.action || "Describe the visual guidance"} className="min-w-0 flex-1 rounded-md border border-border bg-background px-3 py-2 text-sm" /><button type="button" disabled={busy || !active} onClick={() => void search()} className="inline-flex items-center gap-2 rounded-md bg-foreground px-3 py-2 text-sm text-background disabled:opacity-50"><Search className="size-4" />{busy ? "Searching" : "Find images"}</button></div>{error && <p className="text-sm text-destructive">{error}</p>}{references.length > 0 && <div className="grid gap-3 sm:grid-cols-3">{references.map((item) => <article key={item.id} className="overflow-hidden rounded-md border border-border">{item.image_url && <img src={item.image_url} alt="" className="h-32 w-full object-cover" loading="lazy" referrerPolicy="no-referrer" />}<div className="grid gap-1 p-3"><a href={item.source_url} target="_blank" rel="noreferrer" className="text-sm font-medium hover:underline">{item.title}</a><p className="text-xs text-muted-foreground">{item.publisher || "Web source"}</p>{item.snippet && <p className="text-xs text-muted-foreground">{item.snippet}</p>}</div></article>)}</div>}</section>
}
